configured_endpoints: 2
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/leftover-works%2Fhubspot-account-info-ed0d8a0bc863dbf9b29ccc1eae357f6700a821a2c5fe05cc79dcd5a80cdc5bb5.yml
openapi_spec_hash: 46a26b4dde9d76f5a43a32aa17226a76
config_hash: c6873ffd57441afa1a0449dbe26efeab
